name: HelloWorld
version: 1.0
author: Dáire McDermott
main: work.mcdermott.helloworld.Main
description: My first Minecraft spigot plugin.

commands:
  hello:
    aliases:
      - hi
    description: This is the hello command.